package com.lysy.morse;

import java.util.LinkedHashMap;
import java.util.Map;

public class ConstValues {
    protected static final String spaceMark = "   ";

    protected static final Map<String, String> morseKey = new LinkedHashMap<String, String>() {
        {
            put("• — • —", "a");
            put("• —", "ą");
            put("— • • •", "b");
            put("— • — •", "c");
            put("— • — • •", "ć");
            put("— • •", "d");
            put("•", "e");
            put("• • — • •", "ę");
            put("• • — •", "f");
            put("— — •", "g");
            put("• • • •", "h");
            put("• •", "i");
            put("• — — —", "j");
            put("— • —", "k");
            put("• — • •", "l");
            put("• — • • —", "ł");
            put("— —", "m");
            put("— •", "n");
            put("— — • — —", "ń");
            put("— — —", "o");
            put("— — — •", "ó");
            put("• — — •", "p");
            put("— — • —", "q");
            put("• — •", "r");
            put("• • •", "s");
            put("• • • — • • •", "ś");
            put("—", "t");
            put("• • —", "u");
            put("• • • —", "v");
            put("• — —", "w");
            put("— • • —", "x");
            put("— • — —", "y");
            put("— — • •", "z");
            put("— — • • — •", "ż");
            put("— — • • —", "ź");
            put("— — — — —", "0");
            put("• — — — —", "1");
            put("• • — — —", "2");
            put("• • • — —", "3");
            put("• • • • —", "4");
            put("• • • • •", "5");
            put("— • • • •", "6");
            put("— — • • •", "7");
            put("— — — • •", "8");
            put("— — — — •", "9");
            put("• — • — • —", ".");
            put("— — • • — —", ",");
            put("• — • • — •", "\"");
            put("• • — — • —", "_");
            put("• — • — •", "+");
            put("— • • — •", "/");
            put("• • — — • •", "?");
            put("— • — • — —", "!");
            put("— • • • • —", "–");
            put("• — — • — •", "@");
            put("— • • • —", "=");
            put("— • — — •", "(");
            put("— • — — • —", ")");
        }
    };

    protected static final Map<String, String> alphabetKey = new LinkedHashMap<String, String>() {
        {
            put("a", "• — • —");
            put("ą", "• —");
            put("b", "— • • •");
            put("c", "— • — •");
            put("ć", "— • — • •");
            put("d", "— • •");
            put("e", "•");
            put("ę", "• • — • •");
            put("f", "• • — •");
            put("g", "— — •");
            put("h", "• • • •");
            put("i", "• •");
            put("j", "• — — —");
            put("k", "— • —");
            put("l", "• — • •");
            put("ł", "• — • • —");
            put("m", "— —");
            put("n", "— •");
            put("ń", "— — • — —");
            put("o", "— — —");
            put("ó", "— — — •");
            put("p", "• — — •");
            put("q", "— — • —");
            put("r", "• — •");
            put("s", "• • •");
            put("ś", "• • • — • • •");
            put("t", "—");
            put("u", "• • —");
            put("v", "• • • —");
            put("w", "• — —");
            put("x", "— • • —");
            put("y", "— • — —");
            put("z", "— — • •");
            put("ż", "— — • • — •");
            put("ź", "— — • • —");
            put("0", "— — — — —");
            put("1", "• — — — —");
            put("2", "• • — — —");
            put("3", "• • • — —");
            put("4", "• • • • —");
            put("5", "• • • • •");
            put("6", "— • • • •");
            put("7", "— — • • •");
            put("8", "— — — • •");
            put("9", "— — — — •");
            put(".", "• — • — • —");
            put(",", "— — • • — —");
            put("\"", "• — • • — •");
            put("_", "• • — — • —");
            put("+", "• — • — •");
            put("/", "— • • — •");
            put("?", "• • — — • •");
            put("!", "— • — • — —");
            put("–", "— • • • • —");
            put("@", "• — — • — •");
            put("=", "— • • • —");
            put("(", "— • — — •");
            put(")", "— • — — • —");
            put(" ", "    ");
        }
    };
}
